# Generated by Django 3.2.4 on 2021-06-11 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AIweb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='total',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
