# Generated by Django 3.2.4 on 2021-06-11 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AIweb', '0002_alter_sale_total'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sale',
            old_name='total',
            new_name='total_price',
        ),
    ]
