# Generated by Django 3.2.4 on 2021-06-29 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AIweb', '0003_rename_total_sale_total_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
