# Generated by Django 3.2.4 on 2021-06-29 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AIweb', '0004_alter_sale_transaction_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=50000),
        ),
    ]
