# Generated by Django 3.2.4 on 2021-06-29 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AIweb', '0006_alter_sale_transaction_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='csv',
            name='activate',
        ),
        migrations.AddField(
            model_name='csv',
            name='csv_file',
            field=models.FileField(null=True, upload_to='csvs'),
        ),
        migrations.AlterField(
            model_name='csv',
            name='file_name',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
